System.InvalidOperationException: Collection was modified; enumeration operation may not execute. exception fixed in CategorizeJewelSlots
-Might not need to have own method (but still would make it easier to update code later if decide to hold more data for each Jewel Node)